### ISSUE TITLE
Dataset Fairness Checklist Enhancements

### ISSUE THREAD

**Issue by astrong-ldeo** [usap-dc-dev/usap-dc-website#16]
- Change true/false checkbox to Bad/Okay/Good enumerated scale
- Add info to dashboard and landing page
- Add small bit to email template saying the info is ready and where to view it

**Comment by astrong-ldeo** [comment]
Added 3-tier enumerated scale – in prod now.

Added popup for showing FAIRness on the dataset landing page, and another column summarizing the evaluation on the dashboard. Not going to PROD yet.

**Comment by astrong-ldeo** [comment]
Changed 3 to 5 tiers (added TBD and N/A) to the FAIRness sliders, added two more fields, and reordered the fields.

**Comment by astrong-ldeo** [comment]
Next up:
- Show the scores and perhaps the popup on the user dashboard.
- Restrict access – only the owner, collaborators, and curators should be able to see the FAIR scores. Just curators at first!

**Comment by sicordero** [comment]
Evaluating something as "FAIR" data within the FAIRness assessment matrix might be confusing.

Replace "FAIR" with: "Average" or "Okay" or ?

Or make "GOOD" "EXCELLENT" instead, and have "FAIR" become "GOOD"??

**Comment by astrong-ldeo** [comment]
"Fair" is now "Okay"
