### ISSUE TITLE
updates to dataset title should also automatically update project_dataset title

### ISSUE THREAD

**Issue by fnitsche2001** [usap-dc-dev/usap-dc-website#22]
When a dataset is edited and the title is changed the title in in the project dataset table should also be updated.
Currently this is done manually, but might be easy to forget.

**Comment by astrong-ldeo** [comment]
Fixed. Commit: [here](https://github.com/usap-dc-dev/usap-dc-website/commit/13eaf02399854cc8c61f5c9933074d8b4c7ce53d)

**Comment by astrong-ldeo** [comment]
I made a slight mistake – actually fixed [here](https://github.com/usap-dc-dev/usap-dc-website/commit/dec311ee07a9d2c5fa3d64f390f8f2ee4575cf6c)
