### ISSUE TITLE
error message when validating DIF xml in curator tool

### ISSUE THREAD

**Issue by fnitsche2001** [usap-dc-dev/usap-dc-website#24]
I have noticed occasionally an error message when validating DIF xml in the DIF XML curator tool (see attached image.
There seems to be an extra error message "Error saving validated DIF XML" at the end, although the xml seems to be saved correctly to the watch directories. This message only occurs sometimes (when updating existing some project xml files?), but not always. It is unclear what causes this error.
The example is p0010389
![usap-dc_error_dif_save](https://github.com/usap-dc-dev/usap-dc-website/assets/52971708/d8fd6a55-94a1-4fb8-968b-f4eba20e5986)

**Comment by astrong-ldeo** [comment]
This is due to file ownership/permissions issues on the server. Ensure that the user "apache" has write access to the desired file, if it exists, to avoid this problem in the future.
