### ISSUE TITLE
add checks to project registration or project ingestion for existing title and collaborative award numbers

### ISSUE THREAD

**Issue by fnitsche2001** [usap-dc-dev/usap-dc-website#25]
occasionally a user submits a project registration for an award that is part of a collaborative research project for which already a project page exists. I think currently we check only for award number, not title of an award. So we should also check if a project page with the same title already exists.
In addition to this check, I would be great if the curator form can check for any additional award with the same title, so that we can add all the awards for a collaborative research project to a project page even if the submitter only lists one award.

**Comment by astrong-ldeo** [comment]
I think I've added the requested functionality. Check the branch check_award_title for the code changes.
