### ISSUE TITLE
transfer from Seafloor-ph to AWS deep glacier not working

### ISSUE THREAD

**Issue by fnitsche2001** [usap-dc-dev/usap-dc-website#3]
The transfer of large datasets from Seafloor-ph to the AWS deep glacier storage is not working. The scripts to create the bag files work fine but the bag is not moved to the AWS bucket. I am getting a permission denied error.

**Comment by astrong-ldeo** [comment]
The issue was that Neville's AWS credentials were still being used after his account was terminated. We are now using Frank's credentials instead. Eventually, this issue will come up again, and we'll have to switch credentials again, but not likely in the near future.
