### ISSUE TITLE
curator project ingestion of ieda keywords cause sql error

### ISSUE THREAD

**Issue by fnitsche2001** [usap-dc-dev/usap-dc-website#4]
When processing a project registration in the curator pages with a user keyword that matches to an IEDA keyword (e.g. ik-0029) I am getting an error message "Error Importing to database: insert or update on table "project_keyword_map" violates foreign key constraint "keyword_fk" DETAIL: Key (keyword_id)=(ik-0029) is not present in table "keyword_usap". 

(happened with project ingestion https://www.usap-dc.org/curator?uid=p0010406)
My guess is that the project_keyword_map only allows keywords in the keyword_usap table, but not those in the keyword_ieda table.
Not a critical issue. I can comment the problem keywords items out and the SQL runs fine.
We might a address this when cleaning up the keywords in general, e.g. by merging all the keywords in one table.

**Comment by astrong-ldeo** [comment]
Steps:

1. Copy all entries from keyword_ieda to keyword_usap whose keyword_labels are not already in keyword_usap. (SQL, maybe some Python)
2. Update all projects and datasets to use the keyword_usap version of any keywords that were not copied. (SQL, probably some Python as well)
3. Eliminate the ability to choose IEDA versions of the duplicate keywords from the website. (HTML/JS)

Am I missing anything?
