### ISSUE TITLE
modify bi-annual award report for NSF Program Officers

### ISSUE THREAD

**Issue by fnitsche2001** [usap-dc-dev/usap-dc-website#49]
We want to change the bi-annual award report for NSF program manager.
The current version produces reports for the different NSF programs, but awards are not always distributed between the POs just by program (especially at the moment when some positions are filled). It would be better to create award reports directly by the program officer who is handling it.
(we might need to check if the NSF award harvest is updating the database when the PO changes - I think it does this)

The next award harvest is in April 2024. So we should target this task around that time.

**Comment by astrong-ldeo** [comment]
Done. See branch nsf_harvest, and relevant pull requests #61 to #65.
