### ISSUE TITLE
Check NSF Award Harvest API

### ISSUE THREAD

**Issue by sicordero** [usap-dc-dev/usap-dc-website#59]
Is the NSF API not updating properly on their end or our end? Or is this a standalone issue:

In the case of 1745137: CAREER: Cross-Instrument Synthesis of Antarctic Radar Sounding Observations, the award information has not been updated in two ways:

1.  The Ending Date on the [NSF Webpage](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1745137) has been updated to June 30, 2025. However the Award is still marked within our database to end June 30, 2024.
2. The Program Officer / Manager is still Paul Cutler, and should be updated to Kelly Brunt. This change is also reflected on the website, and is also updated in most other awards in our database.

**Comment by astrong-ldeo** [comment]
The issue could be on our end. I just noticed the relevant config file for the NSF awards harvest tells it to only look at reports updated between 10/18/2022 and 4/23/2023.
