### ISSUE TITLE
Curator Page - Save Readme Error

### ISSUE THREAD

**Issue by sicordero** [usap-dc-dev/usap-dc-website#6]
After selecting the "Save Readme" button, I am prompted by "Error updating Read Me file" banner. The Readme file link is available on the dataset page, but empty/blank in preview and when downloaded. 

<img width="1506" alt="Screenshot 2023-03-03 at 4 58 14 PM" src="https://user-images.githubusercontent.com/83235393/222841747-5daedc2a-ceda-4e30-a2fd-faa7c15d32c3.png">

**EDIT:** This is only occurring on the following dataset: https://www.usap-dc.org/view/dataset/601668

**Comment by astrong-ldeo** [comment]
I'll look into this today.

**Comment by sicordero** [comment]
Unsure if related, but currently unable to "Create SQL and Readme" from JSON file for data ingestion now. Screenshot of error attached:
<img width="1506" alt="Screenshot 2023-03-06 at 12 40 57 PM" src="https://user-images.githubusercontent.com/83235393/223189281-5fd383e1-3392-41ee-9ae5-67fc16a2a1e6.png">

**Comment by astrong-ldeo** [comment]
Can you copy and paste that error message as text? I have some suspicions that can't be resolved with just the screenshot.

**Comment by sicordero** [comment]
> Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/web/usap-dc/htdocs/usap.py", line 3052, in curator sql, readme_file = json2sql.json2sql(json_data, uid, curator_id) File "/web/usap-dc/htdocs/lib/json2sql.py", line 851, in json2sql sql = make_sql(data, id, curator) File "/web/usap-dc/htdocs/lib/json2sql.py", line 367, in make_sql cur.execute(query) File "/usr/local/lib64/python3.9/site-packages/psycopg2/extras.py", line 236, in execute return super().execute(query, vars) psycopg2.errors.SyntaxError: syntax error at or near "Siglin" LINE 1: ...abel) = UPPER('the antenna was mounted on a 3x10' Siglin sle... ^

**Comment by astrong-ldeo** [comment]
No worries – now that I look more closely, I should've seen it from the image anyway.

Thanks for pointing this out – it looks like SQL injection, which means we're fortunate it hasn't led to some disastrous consequences. The single quote at the end of 10' is parsed as the end of the string when it shouldn't be.

**Comment by sicordero** [comment]
OH! Good catch! I will change that to feet and see if I can find any more feet/inches within those datasets...

**Comment by astrong-ldeo** [comment]
The issue here is with the code not sanitizing the database input. I have what should be a fix in dev now and should be in production by end of day.

I'm still not entirely sure about the issue with the readme file. It occurs on dev as well, but not when I run it in debug mode. More debugging is required.

**Comment by astrong-ldeo** [comment]
The initial issue seems to be related to the encoding used to write the readme file. There is a long dash ("–") character in the readme in question, which is incompatible with ascii, the default encoding for writing to files. Specifying utf-8 should fix the issue.

**Comment by astrong-ldeo** [comment]
Both issues should be fixed with [the latest merge/commit](https://github.com/usap-dc-dev/usap-dc-website/pull/8). Please test and confirm so I can close the issue.

**Comment by astrong-ldeo** [comment]
Confirmed it works via Slack message. Closing.
